lang:         en
title:        Red Pixel Limited
email:        contact-us@red-pixel-ltd.co.uk
description: >-
  Team of experienced professionals in IT industry that focuses on delivering high quality digital solutions for our clients
copyright:    © 2025 Red Pixel Limited. All rights reserved.<br/><a href="https://find-and-update.company-information.service.gov.uk/company/11212396" target="_blank">GOV.UK Companies House page</a>
advertise:    false

accent_image: /assets/img/sidebar-bg.jpg
accent_color: rgb(79,177,186)
theme_color:  rgb(0,0,0)

google_fonts: false

menu:
  - title:    Learn more
    url:      /index/

author:
  name:       Sergejs Terentjevs    
  social:
    github:   Red-Pixel-Limited
    email:    contact-us@red-pixel-ltd.co.uk

# Build settings
remote_theme: hydecorp/hydejack@v9.1.6
plugins:
  - jekyll-feed
  - jekyll-include-cache

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
